on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
    - created

name: Build

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/') == false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run compile
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run compile
      - run: npm install -g vsce
      - name: Generate extension package
        run: vsce package -o ./xeto-extension.vsix
      - name: Push extension to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./xeto-extension.vsix
          asset_name: extension.vsix
          tag: ${{ github.ref }}
          overwrite: true
      - name: Publish to marketplace
        run: npm run deploy
        env:
         VSCE_PAT: ${{ secrets.VSCE_PAT }}


 

  
